import Head from 'next/head'
import Navbar from '../components/NavBar'
import TopBar from '../components/TopBar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<TopBar />
<Navbar />
      
    </div>
  )
}
